# Generated by Django 4.2.1 on 2023-06-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccines',
            old_name='maximum_age',
            new_name='weeks_maximum_age',
        ),
        migrations.RenameField(
            model_name='vaccines',
            old_name='minimum_age',
            new_name='weeks_minimum_age',
        ),
        migrations.RemoveField(
            model_name='vaccines',
            name='weeks_administered',
        ),
    ]
