# Generated by Django 4.2.1 on 2023-07-07 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_appointment_doctor'),
        ('system', '0004_appointment_cancelled_alter_appointment_doctor'),
    ]

    operations = [
    ]
