# Generated by Django 4.2.1 on 2023-07-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'Children'},
        ),
        migrations.AlterModelOptions(
            name='vaccines',
            options={'verbose_name_plural': 'Vaccines'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.TextField(max_length=500, verbose_name='Feedback'),
        ),
    ]
