# Generated by Django 4.2.1 on 2023-06-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_appointment_parent_vaccination_doctor_child_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
