# Generated by Django 4.2.1 on 2023-07-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_merge_20230707_2148'),
        ('system', '0006_alter_child_options_alter_vaccines_options_and_more'),
    ]

    operations = [
    ]
