# Generated by Django 4.2.1 on 2023-07-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_merge_20230708_0946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomLogEntry',
        ),
    ]
