# Generated by Django 4.2.1 on 2023-07-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_delete_customlogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(null=True, verbose_name='Created on'),
        ),
    ]
