# Generated by Django 4.2.1 on 2023-06-15 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_appointment_parent_alter_child_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
