# Generated by Django 4.2.1 on 2023-07-11 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_feedback_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created on'),
        ),
    ]
