# Generated by Django 4.2.1 on 2023-06-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_delete_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
