# Generated by Django 4.2.1 on 2023-07-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_alter_child_first_name'),
        ('system', '0011_alter_feedback_created'),
    ]

    operations = [
    ]
