# Generated by Django 4.2.1 on 2023-06-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_alter_appointment_status_alter_doctor_appointments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vaccination',
            new_name='Vaccines',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='vaccinations',
            new_name='vaccines',
        ),
    ]
