# Generated by Django 4.2.1 on 2023-06-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_rename_vaccination_vaccines_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccines',
            name='date',
        ),
        migrations.AddField(
            model_name='vaccines',
            name='maximum_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vaccines',
            name='minimum_age',
            field=models.IntegerField(default=0),
        ),
    ]
