# Generated by Django 4.2.1 on 2023-06-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_remove_vaccines_date_vaccines_maximum_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccines',
            name='status',
        ),
    ]
