# Generated by Django 4.2.1 on 2023-06-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_remove_vaccines_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='vaccines',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='system.vaccines'),
        ),
    ]
