# Generated by Django 4.2.1 on 2023-06-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_appointment_vaccines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccines',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
