# Generated by Django 4.2.1 on 2023-06-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_alter_vaccines_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccines',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
