# Generated by Django 4.2.1 on 2023-06-19 14:14

import django.contrib.admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('system', '0019_alter_vaccines_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLogEntry',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='child',
            name='vaccines',
        ),
        migrations.AddField(
            model_name='vaccines',
            name='child',
            field=models.ManyToManyField(to='system.child'),
        ),
    ]
