# Generated by Django 4.2.1 on 2023-06-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_customlogentry_remove_child_vaccines_vaccines_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccines',
            name='child',
        ),
        migrations.AddField(
            model_name='child',
            name='vaccines',
            field=models.ManyToManyField(to='system.vaccines'),
        ),
    ]
