# Generated by Django 4.2.1 on 2023-06-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_profile_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='licence_no',
            field=models.CharField(default='LS360', max_length=10),
        ),
    ]
