# Generated by Django 4.2.1 on 2023-06-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_alter_doctor_licence_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='licence_no',
            new_name='license_no',
        ),
    ]
