# Generated by Django 4.2.1 on 2023-06-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_rename_licence_no_doctor_license_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='vaccines',
            field=models.ManyToManyField(related_name='children', to='system.vaccines'),
        ),
    ]
