# Generated by Django 4.2.1 on 2023-06-24 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0027_alter_child_vaccines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='vaccines',
        ),
        migrations.AddField(
            model_name='vaccines',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='system.child'),
        ),
    ]
