# Generated by Django 4.2.1 on 2023-06-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0028_remove_child_vaccines_vaccines_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccines',
            name='child',
        ),
    ]
