# Generated by Django 4.2.1 on 2023-06-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0030_vaccines_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='administered',
            field=models.BooleanField(default=False),
        ),
    ]
