# Generated by Django 4.2.1 on 2023-06-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0031_appointment_administered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='administered',
        ),
        migrations.AddField(
            model_name='vaccines',
            name='administered',
            field=models.BooleanField(default=False),
        ),
    ]
