# Generated by Django 4.2.1 on 2023-06-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0035_alter_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccines',
            name='administered',
        ),
        migrations.AddField(
            model_name='vaccines',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
