# Generated by Django 4.2.1 on 2023-06-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0037_remove_appointment_status_alter_vaccines_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vaccines',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='', max_length=20),
        ),
    ]
