# Generated by Django 4.2.1 on 2023-06-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0039_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccines',
            name='status',
        ),
    ]
