# Generated by Django 4.2.1 on 2023-06-25 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0042_alter_vaccines_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccines',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='system.child'),
        ),
    ]
